- name: Get current OS version
  when: ansible_system == 'FreeBSD'
  check_mode: no
  ansible.builtin.shell:
    cmd: >-
      uname -v | sed -e 's,^\([^#]*\) #\(.* [1-2][0-9][0-9][0-9]\).*/\([^\]*\) $,\1 (\3) #\2,'
  register: system_motd_uname_shell_result
  changed_when: no

- name: Template Message of the Day
  ansible.builtin.template:
    owner: root
    mode: "0644"
    src: motd/motd.j2
    dest: "/etc/motd"
